name: iplayground19
description: iPlayground 20
version: 2.0.6+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  bloc: ^6.0.3
  flutter_bloc: ^6.0.6
  flutter_markdown: ^0.5.0
  url_launcher: ^5.7.8
  url_launcher_macos: 0.0.1+8
  html2md: ^0.5.1
  shared_preferences: ^0.5.12+2
  shared_preferences_macos: 0.0.1+10
  flutter_local_notifications: ^3.0.1
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  bloc_test: ^7.0.6



flutter:
  uses-material-design: true
  assets:
    - images/nopic.png
    - images/logo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
