name: iplayground19
description: iPlayground 19
version: 2.0.6+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  flutter_markdown: ^0.3.2
  url_launcher: ^5.4.1
  url_launcher_macos: 0.0.1
  html2md: ^0.5.1
  shared_preferences: ^0.5.6
  shared_preferences_macos: 0.0.1
  flutter_local_notifications: ^0.9.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/a_akos_birmacher.png
    - images/a_chiao_te_ni.png
    - images/a_cj_lin.png
    - images/a_daiki_matsudate.png
    - images/a_13一三.png
    - images/a_fengyi.png
    - images/a_han_chang.png
    - images/a_jackychen.png
    - images/a_jeff_lin.png
    - images/a_john_lin.png
    - images/a_kishikawa_katsumi.png
    - images/a_li_heng_hsu.png
    - images/a_lynn.png
    - images/a_mars.png
    - images/a_nelson.png
    - images/a_qing_cheng_li.png
    - images/a_shihting_huang_(neo).png
    - images/a_tinxie_易致.png
    - images/a_yllan.png
    - images/a_yusuke_kita.png
    - images/a_zonble.png
    - images/a_彼得潘.png
    - images/a_徐嘉駿_toby_hsu.png
    - images/a_王巍.png
    - images/a_羊小咩.png
    - images/a_黃惠勤.png
    - images/co_aatp.png
    - images/co_app_girls.png
    - images/co_cocoaheads_tw.png
    - images/co_ios_taipei.png
    - images/co_swift_taipei.png
    - images/logo.png
    - images/s_13.jpg
    - images/s_alice.jpg
    - images/s_allenlai.jpg
    - images/s_annieli.jpg
    - images/s_as.jpg
    - images/s_bigroot.jpeg
    - images/s_bobchang.jpg
    - images/s_chung.png
    - images/s_cindy.jpeg
    - images/s_crystal.jpg
    - images/s_dada.jpg
    - images/s_dan.jpg
    - images/s_dj.jpg
    - images/s_gerry.png
    - images/s_haolee.jpg
    - images/s_hokila.jpg
    - images/s_hy.png
    - images/s_jefferywang.jpg
    - images/s_jimmyliao.jpeg
    - images/s_joechen.jpg
    - images/s_johnnysung.jpg
    - images/s_kennedy.png
    - images/s_limyang.jpg
    - images/s_lukewu.jpg
    - images/s_mackliu.jpg
    - images/s_markfly.png
    - images/s_mike.jpeg
    - images/s_oobe.png
    - images/s_pofat.jpg
    - images/s_roger.jpg
    - images/s_stevensun.jpg
    - images/s_superbil.png
    - images/s_taihsin.jpg
    - images/s_tank.jpg
    - images/s_tobyhsu.jpg
    - images/s_willchen.jpeg
    - images/s_yf.png
    - images/s_yoda.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
